-- Place Check
if game.PlaceId ~= 2753915549 then
	if game.PlaceId == 14775231477 or game.PlaceId == 2753915549 then
        
local OrionLib = loadstring(game:HttpGet(('https://raw.githubusercontent.com/RScriptz/RobloxScripts/main/OrionLibKeybind.lua')))()
	local Window = OrionLib:MakeWindow({
		Name = "🍌Blox Fruits🍌",
		HidePremium = false,
		SaveConfig = true,
		ConfigFolder = "Blox Fruits",
		IntroText = "Unleashing Script..."
	})
	local Tab = Window:MakeTab({
		Name = "Free Gamepasses",
		Icon = "rbxassetid://4483345998",
		PremiumOnly = false
	})
